apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce
  labels:
    app: commerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commerce
  template:
    metadata:
      labels:
        app: commerce
    spec:
      containers:
      - name: commerce
        image: commerce:0.0.4
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: commerce
spec:
  selector:
    app: commerce
  type: NodePort
  ports:
  - name: "http-api"
    port: 8080
    nodePort: 30080

