apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-orders
  labels:
    app: customer-orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-orders
  template:
    metadata:
      labels:
        app: customer-orders
    spec:
      containers:
      - name: customer-orders
        image: customer-orders:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-orders
spec:
  selector:
    app: customer-orders
  ports:
  - name: "http-api"
    port: 8080
