apiVersion: apps/v1
kind: Deployment
metadata:
  name: debtors
  labels:
    app: debtors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: debtors
  template:
    metadata:
      labels:
        app: debtors
    spec:
      containers:
      - name: debtors
        image: debtors:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: debtors
spec:
  selector:
    app: debtors
  ports:
  - name: "http-api"
    port: 8080

