apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: delivery:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
spec:
  selector:
    app: delivery
  ports:
  - name: "http-api"
    port: 8080

