apiVersion: apps/v1
kind: Deployment
metadata:
  name: gift-cards
  labels:
    app: gift-cards
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gift-cards
  template:
    metadata:
      labels:
        app: gift-cards
    spec:
      containers:
      - name: gift-cards
        image: gift-cards:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gift-cards
spec:
  selector:
    app: gift-cards
  ports:
  - name: "http-api"
    port: 8080

