apiVersion: apps/v1
kind: Deployment
metadata:
  name: installments
  labels:
    app: installments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: installments
  template:
    metadata:
      labels:
        app: installments
    spec:
      containers:
      - name: installments
        image: installments:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: installments
spec:
  selector:
    app: installments
  ports:
  - name: "http-api"
    port: 8080

